cmake_minimum_required(VERSION 3.1.2)

set(PROJECT_NAME BSFW)
project(${PROJECT_NAME})

set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_CXX_FLAGS_DEBUG "$ENV{CXXFLAGS} -O0 -Wall -g2 -ggdb")
set(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O0 -Wall -g2 -ggdb")

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)

file(GLOB_RECURSE ${PROJECT_NAME}_SOURCE
		Src/*.cpp)

add_library(${PROJECT_NAME} SHARED ${${PROJECT_NAME}_SOURCE})
target_link_libraries(${PROJECT_NAME} PRIVATE Threads::Threads)

target_include_directories(
	${PROJECT_NAME}
	PRIVATE
	${CMAKE_CURRENT_SOURCE_DIR}
	${CMAKE_CURRENT_SOURCE_DIR}/Src
	${CMAKE_INCLUDE_CURRENT_DIR}
)

install( DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/build DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/bin FILES_MATCHING PATTERN "*.so")

install( DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Export DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/bin FILES_MATCHING PATTERN "*.h")